### ISSUE TITLE
Stretch Goal

### ISSUE THREAD

**Issue by dfelleman811** [210823-java-msa-wvu/sherron_evans_p0#1]
Hi Sherron - your user stories look good. I would like you to add a stretch goal (a feature that you can implement if you have time). I think your application would benefit from tracking all transactions and perhaps giving the employee user the ability to see all transactions. Please update your README.md to include this stretch goal. Thanks!

**Comment by codeBAWSE** [comment]
Thank you, README.md has been updated to include new stretch goal.
